# Base configs
baseurl: "https://fotoreedus.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-76236132-7"

# UI configs
title: "Fotography by Reed Sutton"
subtitle: "See the world through my eyes!"
author: "Reed Taylor Sutton"
header:
 title: "Fotography"
 subtitle: "by Reed Sutton"
footer:
 name: "Hey there, my name is Reed"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/fotoreedus"
  500px: "https://500px.com/fotoreedus"
  instagram: "https://www.instagram.com/fotoreedus"
# dribbble: "https://dribbble.com/ramswaroop"
  twitter: "https://www.twitter.com/reedus33"
  linkedin: "https://in.linkedin.com/in/reed33"
  github: "https://www.github.com/reed33"
